version: "3.1"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - 9090:9000
    environment:
      - SONAR_WEB_CONTEXT=/sonarqube
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions
    networks:
      - frontend
volumes:
  sonar_data:
  sonar_logs:
  sonar_extensions:
networks:
  frontend:
    name: frontend
