version: "3.1"

services:
  sonarqube:
    container_name: alzo-sonarqube
    image: sonarqube:8.9-community
    ports:
      - 9090:9000
      - 9092:9092
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions
volumes:
  sonar_data:
  sonar_logs:
  sonar_extensions:
