version: "3.1"

services:
  web-proxy:
    container_name: nginx-proxy
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - configs:/etc/nginx
    networks:
      - frontend
volumes:
  configs:
networks:
  frontend:
    name: frontend
    external: true
