version: "3.1"

services:
  http-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: http-proxy
    image: http-proxy
    tty: true
    restart: always
    ports:
      - 8080:80
    networks:
      - frontend
networks:
  frontend:
    name: frontend
