services:
  portainer:
    container_name: portainer-manager
    image: portainer/portainer-ce:alpine
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - frontend
networks:
  frontend:
    name: frontend
