version: "3.1"

services:
  db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
