version: '3.1'

services:
  redis-server:
    container_name: redis-server
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/usr/local/etc/redis

volumes:
  redis_data: